sky:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    host: localhost
    port: 3306
    database: sky_take_out
    username: root
    password: "031106"
  alioss:
    endpoint: oss-cn-hangzhou.aliyuncs.com
    access-key-id: LTAI5t5ZCfHUQaGSajUUsFvw
    
    bucket-name: web-joe
  redis:
    host: localhost
    port: 6379
    password: '031106'
    database: 8